name: Deploy to Cloud Run

on:
  push:
    branches:
      - prod-gcp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/cye-tech-457716/next-app/next-app:$GITHUB_SHA .
          docker push us-central1-docker.pkg.dev/cye-tech-457716/next-app/next-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy next-app \
            --image=us-central1-docker.pkg.dev/cye-tech-457716/next-app/next-app:$GITHUB_SHA \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
