name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - prod-gcp

jobs:
  deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cye-tech-457716
          install_components: "beta"

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Verify Dockerfile exists
        run: |
          echo "Contenido de directorio:"
          ls -al
          echo "Contenido del Dockerfile:"
          cat Dockerfile

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/cye-tech-457716/next-app-repo/next-app:$GITHUB_SHA .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/cye-tech-457716/next-app-repo/next-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy next-app \
            --image us-central1-docker.pkg.dev/cye-tech-457716/next-app-repo/next-app:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project cye-tech-457716
