name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - prod-gcp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/cye-tech-457716/next-app .

      - name: Push Docker image
        run: |
          docker push gcr.io/cye-tech-457716/next-app

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: next-app
          image: gcr.io/cye-tech-457716/next-app
          region: us-central1
